go.property("speed", 150)

function init(self)

	self.input = {
		left = false,
		right = false,
		front = false,
		back = false
	}

	self.vel = vmath.vector(0, 0, 0)
end

function update(self, dt)
	local dir = vmath.vector3()
	if self.input.left then dir.x = dir.x - 1 end
	if self.input.right then dir.x = dir.x + 1 end
	if self.input.front then dir.x = dir.x + 1 end
	if self.input.back then dir.x = dir.x - 1 end
	if dir.x ~= 0 then
		dir = vmath.normalize(dir) 
		go.set_position(go.get_position() + dir * self.speed * dt)
		local movimento = vmath.vector3(dir.x * self.speed * dt, self.vel.y * dt, 0)
		go.set_position(go.get_position() + movimento)
	end
end

function on_input(self, action_id, action)
	if action_id == hash("left") then
		if action.pressed then
			self.input.left = true 
		elseif action.released then
			self.input.left = false
	end
	if action_id == hash("right") then
		if action.pressed then
			self.input.right = true 
		elseif action.released then
			self.input.right = false
	end
	if action_id == hash("front") then
			if action.pressed then
				self.input.front = true 
			elseif action.released then
				self.input.front = false
	end	
	if action_id == hash("back") then
			if action.pressed then
				self.input.back = true 
			elseif action.released then
				self.input.back = false
	end
end
		